repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.10
    hooks:
      - id: terraform-fmt
      - id: tflint
      - id: shellcheck
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
      - id: terraform_docs
      - id: terraform_tfsec